#!/usr/bin/env python3
"""Refresh bundled GPU pci.ids data from an upstream pci.ids source.

This script extracts full device coverage for selected GPU vendors while keeping
runtime behavior offline-only. It is intended for maintainer use during release
prep and can read from a local file or HTTP(S) URL.
"""

from __future__ import annotations

import argparse
import io
import sys
import urllib.request
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


DEFAULT_SOURCE_URL = "https://pci-ids.ucw.cz/v2.2/pci.ids"
DEFAULT_VENDORS = ("10DE", "1002", "8086")


@dataclass
class ParseStats:
    vendors_seen: int = 0
    devices_seen: int = 0
    devices_written: int = 0


def _read_source_text(source: str) -> str:
    if source.startswith("http://") or source.startswith("https://"):
        with urllib.request.urlopen(source, timeout=30) as resp:  # nosec B310
            data = resp.read()
        return data.decode("utf-8", errors="ignore")

    path = Path(source)
    return path.read_text(encoding="utf-8", errors="ignore")


def _parse_vendor_devices(text: str, vendor_filter: Iterable[str]) -> Tuple[Dict[str, str], Dict[str, Dict[str, str]], ParseStats]:
    vendors_target = {v.upper() for v in vendor_filter}
    vendor_names: Dict[str, str] = {}
    devices: Dict[str, Dict[str, str]] = {v: {} for v in vendors_target}
    stats = ParseStats()

    current_vendor: str | None = None

    for raw in io.StringIO(text):
        line = raw.rstrip("\n")
        if not line or line.startswith("#"):
            continue

        # Top-level vendor line: "10de  NVIDIA Corporation"
        if not line.startswith("\t"):
            parts = line.split(None, 1)
            if len(parts) != 2 or len(parts[0]) != 4:
                current_vendor = None
                continue
            vendor_id = parts[0].upper()
            current_vendor = vendor_id if vendor_id in vendors_target else None
            if current_vendor:
                vendor_names[current_vendor] = parts[1].strip()
                stats.vendors_seen += 1
            continue

        # Ignore subsystem lines (double-tab) and non-vendor contexts.
        if line.startswith("\t\t") or current_vendor is None:
            continue

        device_parts = line.strip().split(None, 1)
        if len(device_parts) != 2 or len(device_parts[0]) != 4:
            continue

        device_id = device_parts[0].upper()
        device_name = device_parts[1].strip()
        devices[current_vendor][device_id] = device_name
        stats.devices_seen += 1

    return vendor_names, devices, stats


def _render_pci_ids(vendor_names: Dict[str, str], devices: Dict[str, Dict[str, str]], source: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: List[str] = []
    out.append("# Bundled GPU-focused pci.ids subset")
    out.append("# Generated by scripts/refresh-pci-ids.py")
    out.append(f"# Source: {source}")
    out.append(f"# Refreshed: {now} UTC")
    out.append("")

    for vendor_id in sorted(devices.keys()):
        vendor_name = vendor_names.get(vendor_id, vendor_id)
        out.append(f"{vendor_id.lower()}  {vendor_name}")
        for device_id in sorted(devices[vendor_id].keys()):
            out.append(f"\t{device_id.lower()}  {devices[vendor_id][device_id]}")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh bundled GPU pci.ids data")
    parser.add_argument(
        "--source",
        default=DEFAULT_SOURCE_URL,
        help="Source pci.ids URL or local file path",
    )
    parser.add_argument(
        "--output",
        default="plugins/module_utils/pci.ids",
        help="Output path for generated pci.ids subset",
    )
    parser.add_argument(
        "--vendors",
        nargs="+",
        default=list(DEFAULT_VENDORS),
        help="Vendor IDs to include (default: 10DE 1002 8086)",
    )
    args = parser.parse_args()

    text = _read_source_text(args.source)
    vendor_names, devices, stats = _parse_vendor_devices(text, args.vendors)

    rendered = _render_pci_ids(vendor_names, devices, args.source)
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(rendered, encoding="utf-8")

    devices_total = sum(len(v) for v in devices.values())
    stats.devices_written = devices_total

    print("Refreshed pci.ids")
    print(f"  source: {args.source}")
    print(f"  output: {out_path}")
    print(f"  vendors: {', '.join(sorted(devices.keys()))}")
    print(f"  devices written: {stats.devices_written}")

    # Non-zero exit when nothing was captured is safer for release automation.
    if stats.devices_written == 0:
        print("ERROR: no device IDs were parsed; refusing empty output", file=sys.stderr)
        return 2

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
